"""Fetch ITviec's /jobs-expertise-index and build slug→group mapping.

ITviec organizes expertise under top-level groups like 'Web Application
Development', 'Cybersecurity'. Each group has a <div class="head-divider">
heading followed by a <ul class="skill-tag-list"> of expertise links.

The mapping is written to services/crawler_service/services/role_groups.py
and imported by itviec_crawler.py at runtime.

Run periodically (e.g. monthly) to capture new expertise areas:
    python -m services.crawler_service.scripts.build_role_mapping
"""
import json
import sys
from pathlib import Path

import cloudscraper
from bs4 import BeautifulSoup, NavigableString, Tag

sys.path.append(str(Path(__file__).parent.parent.parent.parent))


def _slugify_group(name: str) -> str:
    """Turn 'Data Science & AI / Machine Learning' into 'data_science_ai_ml'."""
    import re
    s = name.lower().replace("&", "and").replace("/", " ")
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    return s


def fetch_mapping() -> dict[str, dict]:
    """Return {slug: {"name": display_name, "group": group_slug, "group_name": group_display}}."""
    s = cloudscraper.create_scraper(
        browser={"browser": "chrome", "platform": "linux", "mobile": False}
    )
    r = s.get("https://itviec.com/jobs-expertise-index", timeout=20)
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")

    mapping: dict[str, dict] = {}
    # Walk the document; track the most recent group divider, attach following <ul> links to it.
    current_group_name: str | None = None
    container = soup.select_one("div.jobs-by-expertise") or soup

    for el in container.descendants:
        if not isinstance(el, Tag):
            continue
        if el.name == "div" and "head-divider-text" in (el.get("class") or []):
            current_group_name = el.get_text(strip=True)
            continue
        if el.name == "a" and current_group_name:
            href = el.get("href", "")
            if not href.startswith("/it-jobs/") or "?" in href:
                continue
            slug = href.replace("/it-jobs/", "")
            if not slug:
                continue
            mapping[slug] = {
                "name": el.get_text(strip=True),
                "group": _slugify_group(current_group_name),
                "group_name": current_group_name,
            }
    return mapping


def emit_python_module(mapping: dict[str, dict]) -> str:
    """Render the mapping as a Python module with constant dict literals."""
    lines = [
        '"""Role slug → group mapping for ITviec expertise areas.',
        "",
        "Auto-generated by scripts/build_role_mapping.py — do not edit by hand.",
        f'Source: https://itviec.com/jobs-expertise-index ({len(mapping)} expertise areas).',
        '"""',
        "",
        "# slug → {name, group, group_name}",
        "ROLE_GROUPS = " + json.dumps(mapping, indent=4, ensure_ascii=False, sort_keys=True),
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    mapping = fetch_mapping()
    print(f"# {len(mapping)} expertise areas across "
          f"{len({m['group'] for m in mapping.values()})} groups",
          file=sys.stderr)

    # Group counts
    from collections import Counter
    counts = Counter(m["group_name"] for m in mapping.values())
    for name, n in sorted(counts.items(), key=lambda x: -x[1]):
        print(f"#   {name}: {n}", file=sys.stderr)

    out_path = Path(__file__).parent.parent / "services" / "role_groups.py"
    out_path.write_text(emit_python_module(mapping), encoding="utf-8")
    print(f"# Wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
