"""
Task 3.2: ATS-Compliant PDF CV Generator.
Generates clean, professional PDFs from structured CV data extracted by NER.
Uses a highly customized FPDF2 engine to render resumes that look EXACTLY like
the LaTeX template design (deep blue primary, red secondary, right-aligned dates,
clean headers) without requiring heavy system LaTeX packages.
"""

import io
import os
import re
import shutil
import tempfile
import logging
import subprocess
from typing import Optional, List, Dict, Any
from datetime import datetime

logger = logging.getLogger(__name__)

try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False
    logger.warning("fpdf2 not installed. FPDF generator will be unavailable. Install with: pip install fpdf2")


# ─── COLOR PALETTE (Matched 1:1 with LaTeX template) ────────────────────────
COLOR_PRIMARY = (0, 51, 102)     # Deep Blue (#003366)
COLOR_SECONDARY = (180, 0, 0)   # Red Highlights (#B40000)
COLOR_TEXT = (30, 30, 30)        # Dark Charcoal (#1E1E1E)
COLOR_MUTED = (80, 80, 80)       # Dark Gray (#505050)
COLOR_LIGHT_GRAY = (245, 245, 245) # Light gray for section rules


class ATSResumePDF(FPDF):
    """ATS-friendly PDF layout mimicking the LaTeX template precisely with full Vietnamese support."""

    def __init__(self):
        super().__init__()
        # Set tight geometric margins matching the LaTeX geometry package
        self.set_margins(left=12, top=10, right=12)
        self.set_auto_page_break(auto=True, margin=10)
        
        # Register DejaVuSans TrueType fonts for full Unicode and Vietnamese accent support
        self.add_font("DejaVu", "", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")
        self.add_font("DejaVu", "B", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf")
        self.add_font("DejaVu", "I", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf")
        self.add_font("DejaVu", "BI", "/usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf")
        self.set_font("DejaVu", "", 9.5)

    def header(self):
        pass  # No header for ATS compliance

    def footer(self):
        self.set_y(-10)
        self.set_font("DejaVu", "I", 7.5)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f"Generated by Resume Assistant | {datetime.now().strftime('%Y-%m-%d')}", align="C")

    def add_name(self, name: str):
        self.set_font("DejaVu", "B", 22)
        self.set_text_color(*COLOR_PRIMARY)
        self.cell(0, 10, name.upper(), align="C", new_x="LMARGIN", new_y="NEXT")

    def add_role(self, role: str):
        self.set_font("DejaVu", "B", 12.5)
        self.set_text_color(*COLOR_SECONDARY)
        self.cell(0, 6, role, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def add_contact_line(self, text: str):
        self.set_font("DejaVu", "", 9)
        self.set_text_color(*COLOR_TEXT)
        self.cell(0, 4.5, text, align="C", new_x="LMARGIN", new_y="NEXT")

    def add_section_header(self, title: str):
        self.ln(4)
        self.set_font("DejaVu", "B", 11)
        self.set_text_color(*COLOR_PRIMARY)
        self.cell(0, 6, title.upper(), new_x="LMARGIN", new_y="NEXT")
        # Draw light gray divider rule under heading mimicking \titlerule
        self.set_draw_color(*COLOR_LIGHT_GRAY)
        self.set_line_width(0.8)
        y = self.get_y() - 0.5
        self.line(12, y, 198, y)
        self.ln(2)

    def add_subsection(self, title: str, subtitle: str = "", date_range: str = "", 
                       job_mode: str = "", location_mode: str = "", team_size: str = "", 
                       is_nda: bool = False, custom_links: list = None):
        # Left-aligned bold job title or project name
        self.set_font("DejaVu", "B", 10)
        self.set_text_color(*COLOR_PRIMARY)
        
        current_y = self.get_y()
        self.set_x(12)
        
        title_str = title
        if is_nda:
            title_str += " [NDA]"
        self.cell(0, 5, title_str)
        
        # Right-aligned date range
        if date_range:
            self.set_font("DejaVu", "", 9.5)
            self.set_text_color(*COLOR_MUTED)
            self.set_y(current_y)
            self.cell(0, 5, date_range, align="R", new_x="LMARGIN", new_y="NEXT")
        else:
            self.ln(5)
            
        # Subtitle / Company / Stack description on next line
        sub_parts = []
        if subtitle:
            sub_parts.append(subtitle)
        if job_mode:
            sub_parts.append(job_mode)
        if location_mode:
            sub_parts.append(location_mode)
        if team_size:
            sub_parts.append(f"Team size: {team_size}")
            
        sub_text = "  ·  ".join(sub_parts)
        
        # Add links inside subtext or right-aligned if they exist
        links_text = ""
        if custom_links:
            link_parts = []
            for l in custom_links:
                lbl = l.get("title") or l.get("url", "").replace("https://", "").replace("http://", "").replace("www.", "")
                if lbl:
                    link_parts.append(lbl)
            if link_parts:
                links_text = " | ".join(link_parts)
                
        if sub_text:
            self.set_font("DejaVu", "", 9)
            self.set_text_color(*COLOR_MUTED)
            self.cell(130, 4.5, sub_text)
            
            if links_text:
                self.set_font("DejaVu", "B", 9)
                self.set_text_color(180, 0, 0) # secondary (Red)
                self.cell(0, 4.5, links_text, align="R", new_x="LMARGIN", new_y="NEXT")
            else:
                self.ln(4.5)
        elif links_text:
            self.set_font("DejaVu", "B", 9)
            self.set_text_color(180, 0, 0) # secondary (Red)
            self.cell(0, 4.5, links_text, align="R", new_x="LMARGIN", new_y="NEXT")
        else:
            if subtitle:
                self.ln(4.5)

        self.ln(0.5)

    def add_bullet_point(self, text: str):
        self.set_font("DejaVu", "", 9.5)
        self.set_text_color(*COLOR_TEXT)
        self.set_x(16) # Indented bullet list
        self.multi_cell(0, 4.5, f"- {text}", new_x="LMARGIN", new_y="NEXT")

    def add_paragraph(self, text: str):
        self.set_font("DejaVu", "", 9.5)
        self.set_text_color(*COLOR_TEXT)
        self.multi_cell(0, 4.5, text, new_x="LMARGIN", new_y="NEXT")
        self.ln(0.5)

    def add_skills_line(self, category: str, skills: List[str]):
        self.set_font("DejaVu", "B", 9.5)
        self.set_text_color(*COLOR_TEXT)
        cat_width = self.get_string_width(category + ": ") + 1
        self.cell(cat_width, 5, f"{category}: ")
        self.set_font("DejaVu", "", 9.5)
        self.set_text_color(*COLOR_TEXT)
        self.multi_cell(0, 5, ", ".join(skills), new_x="LMARGIN", new_y="NEXT")


def parse_anchor(anchor: str):
    """
    Smart regex parser to extract job titles, subtitles/companies, and dates from the raw anchor.
    E.g. 'Backend .NET Developer, Smart Sports Tablet (SST) (Jan 2026 -- Jun 2026)'
    """
    # 1. Extract dates inside parenthesis at the end of string
    date_match = re.search(r'\(([^)]*(?:20\d\d|19\d\d|Present)[^)]*)\)\s*$', anchor)
    date_range = ""
    title_part = anchor
    if date_match:
        date_range = date_match.group(1).replace("--", "–")
        title_part = anchor[:date_match.start()].strip().rstrip(",")
    
    # 2. Split role and company by comma
    parts = title_part.split(",", 1)
    if len(parts) == 2:
        return parts[0].strip(), parts[1].strip(), date_range
    return title_part, "", date_range


def generate_fpdf_pdf(cv_data: dict) -> Optional[bytes]:
    """Lightweight, pixel-perfect FPDF-based PDF generator matching LaTeX styling."""
    if not HAS_FPDF:
        logger.error("fpdf2 not installed. Cannot generate FPDF PDF.")
        return None

    try:
        pdf = ATSResumePDF()
        pdf.add_page()

        # ─── Name & Contact (LaTeX styled) ────────────────
        name = cv_data.get("name", "")
        if name:
            pdf.add_name(name)
            
        role = cv_data.get("role", "")
        if not role:
            # Fallback to title from personal info or first Job Title
            role = cv_data.get("title", "Software Developer")
        pdf.add_role(role)

        # 2-Row Contact Information Grid matching LaTeX layout
        row1_parts = []
        if cv_data.get("phone"):
            row1_parts.append(cv_data["phone"])
        if cv_data.get("email"):
            row1_parts.append(cv_data["email"])
        if cv_data.get("location"):
            row1_parts.append(cv_data["location"])
        
        row2_parts = []
        if cv_data.get("linkedin"):
            lbl = cv_data.get("linkedin_title") or cv_data["linkedin"].replace("https://", "").replace("http://", "").replace("www.", "")
            row2_parts.append(lbl)
        if cv_data.get("github"):
            lbl = cv_data.get("github_title") or cv_data["github"].replace("https://", "").replace("http://", "").replace("www.", "")
            row2_parts.append(lbl)
        if cv_data.get("youtube"):
            lbl = cv_data.get("youtube_title") or cv_data["youtube"].replace("https://", "").replace("http://", "").replace("www.", "")
            row2_parts.append(lbl)

        if row1_parts:
            pdf.add_contact_line("   |   ".join(row1_parts))
        if row2_parts:
            pdf.add_contact_line("   |   ".join(row2_parts))
        pdf.ln(1)

        # ─── Professional Summary ────────────────────────
        summary = cv_data.get("summary", "")
        if summary:
            pdf.add_section_header("Professional Summary")
            pdf.add_paragraph(summary)

        # ─── Technical Skills (tabularx style) ────────────
        skills = cv_data.get("skills", {})
        if skills:
            pdf.add_section_header("Technical Skills")
            if isinstance(skills, dict):
                for category, skill_list in skills.items():
                    if skill_list:
                        pdf.add_skills_line(category, skill_list)
            elif isinstance(skills, list):
                pdf.add_paragraph(", ".join(skills))

        # ─── Languages ────────────────────────────────────
        languages = cv_data.get("languages", [])
        if languages:
            pdf.add_section_header("Languages")
            for lang in languages:
                name = lang.get("name", "")
                desc = lang.get("description", "")
                link = lang.get("link", "")
                link_title = lang.get("link_title", "View Certificate")
                
                pdf.set_font("DejaVu", "B", 9.5)
                pdf.set_text_color(*COLOR_TEXT)
                name_width = pdf.get_string_width(name + ": ") + 1
                pdf.cell(name_width, 5, f"{name}: ")
                
                pdf.set_font("DejaVu", "", 9.5)
                if link:
                    pdf.write(5, desc + " ")
                    pdf.set_font("DejaVu", "B", 9.5)
                    pdf.set_text_color(*COLOR_SECONDARY)
                    pdf.cell(0, 5, f"[{link_title}]", link=link, new_x="LMARGIN", new_y="NEXT")
                else:
                    pdf.multi_cell(0, 5, desc, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

        # ─── Experience & Projects ────────────────────────
        experience = cv_data.get("experience", [])
        if experience:
            pdf.add_section_header("Experience & Projects")
            for exp in experience:
                anchor = exp.get("anchor", "")
                entities = exp.get("entities", [])
                
                orgs = [e["text"] for e in entities if e.get("type") == "ORG"]
                dates = [e["text"] for e in entities if e.get("type") == "DATE"]
                skills = [e["text"] for e in entities if e.get("type") == "SKILL"]
                
                org = ", ".join(orgs) if orgs else ""
                date_range = " - ".join(dates) if dates else ""
                skills_val = ", ".join(skills) if skills else ""
                
                if not entities:
                    title, org, date_range = parse_anchor(anchor)
                else:
                    title = anchor
                
                job_mode = exp.get("job_mode", "")
                location_mode = exp.get("location_mode", "")
                team_size = exp.get("team_size", "")
                is_nda = exp.get("is_nda", False)
                custom_links = exp.get("custom_links", [])
                if not custom_links:
                    raw_links = [e["text"] for e in entities if e.get("type") == "LINK"]
                    custom_links = [{"url": u, "title": ""} for u in raw_links]
                
                pdf.add_subsection(title, org, date_range, 
                                   job_mode=job_mode, location_mode=location_mode, 
                                   team_size=team_size, is_nda=is_nda, custom_links=custom_links)

                if skills_val:
                    pdf.set_font("DejaVu", "B", 9)
                    pdf.set_text_color(*COLOR_TEXT)
                    pdf.set_x(16)
                    pdf.write(4.5, "Stack: ")
                    pdf.set_font("DejaVu", "", 9)
                    pdf.write(4.5, skills_val + "\n")
                    pdf.ln(0.5)

                desc = exp.get("description", "")
                if desc:
                    lines = [l.strip() for l in desc.replace("•", "\n").replace("- ", "\n").split("\n") if l.strip()]
                    for line in lines:
                        line_clean = line.lstrip("-•* ").strip()
                        if line_clean:
                            pdf.add_bullet_point(line_clean)
                pdf.ln(1)

        # ─── Projects (If separate) ──────────────────────
        projects = cv_data.get("projects", [])
        if projects:
            if not experience:
                pdf.add_section_header("Projects")
            for proj in projects:
                anchor = proj.get("anchor", "")
                entities = proj.get("entities", [])
                
                orgs = [e["text"] for e in entities if e.get("type") == "ORG"]
                dates = [e["text"] for e in entities if e.get("type") == "DATE"]
                skills = [e["text"] for e in entities if e.get("type") == "SKILL"]
                
                org = ", ".join(orgs) if orgs else ""
                date_range = " - ".join(dates) if dates else ""
                skills_val = ", ".join(skills) if skills else ""
                
                if not entities:
                    title, org, date_range = parse_anchor(anchor)
                else:
                    title = anchor
                
                job_mode = proj.get("job_mode", "")
                location_mode = proj.get("location_mode", "")
                team_size = proj.get("team_size", "")
                is_nda = proj.get("is_nda", False)
                custom_links = proj.get("custom_links", [])
                if not custom_links:
                    raw_links = [e["text"] for e in entities if e.get("type") == "LINK"]
                    custom_links = [{"url": u, "title": ""} for u in raw_links]
                
                pdf.add_subsection(title, org, date_range, 
                                   job_mode=job_mode, location_mode=location_mode, 
                                   team_size=team_size, is_nda=is_nda, custom_links=custom_links)

                if skills_val:
                    pdf.set_font("DejaVu", "B", 9)
                    pdf.set_text_color(*COLOR_TEXT)
                    pdf.set_x(16)
                    pdf.write(4.5, "Stack: ")
                    pdf.set_font("DejaVu", "", 9)
                    pdf.write(4.5, skills_val + "\n")
                    pdf.ln(0.5)
                
                desc = proj.get("description", "")
                if desc:
                    lines = [l.strip() for l in desc.replace("•", "\n").replace("- ", "\n").split("\n") if l.strip()]
                    for line in lines:
                        line_clean = line.lstrip("-•* ").strip()
                        if line_clean:
                            pdf.add_bullet_point(line_clean)
                pdf.ln(1)

        # ─── Education ───────────────────────────────────
        education = cv_data.get("education", [])
        if education:
            pdf.add_section_header("Education")
            for edu in education:
                anchor = edu.get("anchor", "")
                entities = edu.get("entities", [])
                
                orgs = [e["text"] for e in entities if e.get("type") == "ORG"]
                dates = [e["text"] for e in entities if e.get("type") == "DATE"]
                
                org = ", ".join(orgs) if orgs else ""
                date_range = " - ".join(dates) if dates else ""
                
                if not entities:
                    title, org, date_range = parse_anchor(anchor)
                else:
                    title = anchor
                
                custom_links = edu.get("custom_links", [])
                if not custom_links:
                    raw_links = [e["text"] for e in entities if e.get("type") == "LINK"]
                    custom_links = [{"url": u, "title": ""} for u in raw_links]
                
                pdf.add_subsection(title, org, date_range, custom_links=custom_links)
                
                desc = edu.get("description", "")
                if desc:
                    pdf.add_paragraph(desc)

        # ─── Certifications & Achievements ────────────────
        certifications = cv_data.get("certifications", [])
        if certifications:
            pdf.add_section_header("Certifications & Achievements")
            for cert in certifications:
                if isinstance(cert, dict):
                    anchor = cert.get("anchor", "")
                    entities = cert.get("entities", [])
                    
                    orgs = [e["text"] for e in entities if e.get("type") == "ORG"]
                    dates = [e["text"] for e in entities if e.get("type") == "DATE"]
                    
                    org = ", ".join(orgs) if orgs else ""
                    date_range = " - ".join(dates) if dates else ""
                    
                    if not entities:
                        title, org, date_range = parse_anchor(anchor)
                    else:
                        title = anchor
                        
                    custom_links = cert.get("custom_links", [])
                    if not custom_links:
                        raw_links = [e["text"] for e in entities if e.get("type") == "LINK"]
                        custom_links = [{"url": u, "title": "View Certificate"} for u in raw_links]
                    
                    desc = cert.get("description", "")
                    
                    cert_lbl = title
                    if date_range:
                        cert_lbl += f" ({date_range})"
                    
                    pdf.add_subsection(cert_lbl, org, "", custom_links=custom_links)
                    if desc:
                        pdf.add_paragraph(desc)
                elif isinstance(cert, str):
                    pdf.add_bullet_point(cert)

        return pdf.output()

    except Exception as e:
        logger.error(f"FPDF generation failed: {e}")
        return None


def generate_latex_source(cv_data: dict) -> str:
    """Generate professional LaTeX code exactly matching the user's template style."""
    def esc(text: str) -> str:
        if not isinstance(text, str):
            return ""
        chars = {
            "&": "\\&",
            "%": "\\%",
            "$": "\\$",
            "#": "\\#",
            "_": "\\_",
            "{": "\\{",
            "}": "\\}",
            "~": "\\textasciitilde{}",
            "^": "\\textasciicircum{}",
            "\\": "\\textbackslash{}",
        }
        return "".join(chars.get(c, c) for c in text)

    name = esc(cv_data.get("name", "HA VAN DUNG")).upper()
    email = esc(cv_data.get("email", ""))
    phone = esc(cv_data.get("phone", ""))
    location = esc(cv_data.get("location", ""))
    linkedin = esc(cv_data.get("linkedin", ""))
    linkedin_title = esc(cv_data.get("linkedin_title", ""))
    github = esc(cv_data.get("github", ""))
    github_title = esc(cv_data.get("github_title", ""))
    youtube = esc(cv_data.get("youtube", ""))
    youtube_title = esc(cv_data.get("youtube_title", ""))
    role = esc(cv_data.get("role", "Fresher Backend Developer"))

    tex = r"""% Generated dynamically by Resume Assistant
\documentclass[10pt,a4paper]{article}

\usepackage[top=0.8cm, bottom=0.8cm, left=1.2cm, right=1.2cm]{geometry}
\usepackage{enumitem}
\usepackage{titlesec}
\usepackage{xcolor}
\usepackage{hyperref}
\usepackage{tabularx}
\usepackage{microtype}
\usepackage{fontawesome5}
\usepackage{tcolorbox}

\usepackage[defaultsans,scale=0.95]{opensans}
\renewcommand\familydefault{\sfdefault}
\linespread{1.05}

\definecolor{primary}{RGB}{0, 51, 102}    % Deep Blue
\definecolor{secondary}{RGB}{180, 0, 0}   % Red Highlights
\definecolor{text}{RGB}{30, 30, 30}
\definecolor{lightgray}{RGB}{245, 245, 245}
\definecolor{darkgray}{RGB}{80, 80, 80}

\hypersetup{
    colorlinks=true,
    linkcolor=primary,
    urlcolor=primary,
    pdftitle={""" + name + r""" - Resume}
}

\titleformat{\section}
    {\large\bfseries\color{primary}\uppercase}
    {}{0em}
    {}
    [{\color{lightgray}\titlerule[1pt]}]
\titlespacing{\section}{0pt}{8pt}{6pt}

\newcommand{\contactinfo}[2]{
    \makebox[0pt][l]{\textcolor{secondary}{#1}}%
    \hspace{14pt}#2
}

\begin{document}
\pagestyle{empty}

\begin{center}
    {\fontsize{24}{28}\bfseries\color{primary} """ + name + r"""}\\[4pt]
    {\Large\textcolor{secondary}{""" + role + r"""}}\\[4pt]

    \small
    \begin{tabular}{c c c}
"""
    contacts = []
    if phone: contacts.append(rf"\contactinfo{{\faPhone}}{{{phone}}}")
    if email: contacts.append(rf"\contactinfo{{\faEnvelope}}{{\href{{mailto:{email}}}{{{email}}}}}")
    if location: contacts.append(rf"\contactinfo{{\faMapMarkerAlt}}{{{location}}}")
    
    tex += "        " + " & \n        ".join(contacts) + " \\\\\n"
    
    contacts2 = []
    if linkedin:
        lbl = linkedin_title if linkedin_title else linkedin.replace("https://", "").replace("http://", "").replace("www.", "")
        url = linkedin if linkedin.startswith("http") else f"https://{linkedin}"
        contacts2.append(rf"\contactinfo{{\faLinkedin}}{{\href{{{url}}}{{{lbl}}}}}")
    if github:
        lbl = github_title if github_title else github.replace("https://", "").replace("http://", "").replace("www.", "")
        url = github if github.startswith("http") else f"https://{github}"
        contacts2.append(rf"\contactinfo{{\faGithub}}{{\href{{{url}}}{{{lbl}}}}}")
    if youtube:
        lbl = youtube_title if youtube_title else youtube.replace("https://", "").replace("http://", "").replace("www.", "")
        url = youtube if youtube.startswith("http") else f"https://{youtube}"
        contacts2.append(rf"\contactinfo{{\faYoutube}}{{\href{{{url}}}{{{lbl}}}}}")
    
    if contacts2:
        tex += "        " + " & \n        ".join(contacts2) + "\n"
        
    tex += r"""    \end{tabular}
\end{center}

\vspace{2pt}
"""

    summary = esc(cv_data.get("summary", ""))
    if summary:
        tex += r"\section{Professional Summary}" + "\n"
        tex += summary + "\n\n"

    skills = cv_data.get("skills", {})
    if skills:
        tex += r"""\section{Technical Skills}
\begin{tabularx}{\textwidth}{@{}l X@{}}
"""
        if isinstance(skills, dict):
            for cat, s_list in skills.items():
                if s_list:
                    tex += f"    \\textbf{{{esc(cat)}}}: & {esc(', '.join(s_list))} \\\\\n"
        elif isinstance(skills, list):
            tex += f"    \\textbf{{Skills}}: & {esc(', '.join(skills))} \\\\\n"
        
        tex += r"""\end{tabularx}
\vspace{2pt}
"""

    languages = cv_data.get("languages", [])
    if languages:
        tex += r"\section{Languages}" + "\n"
        tex += r"\noindent" + "\n"
        for lang in languages:
            name = esc(lang.get("name", ""))
            desc = esc(lang.get("description", ""))
            link = esc(lang.get("link", ""))
            link_title = esc(lang.get("link_title", "View Certificate"))
            
            tex += rf"\textbf{{{name}}}: {desc}"
            if link:
                tex += rf" \href{{{link}}}{{\textcolor{{secondary}}{{\scriptsize \faExternalLink* {link_title}}}}}"
            tex += r"\\" + "\n"
        tex += "\n"

    experience = cv_data.get("experience", [])
    if experience:
        tex += r"\section{Experience \& Projects}" + "\n"
        for exp in experience:
            anchor = esc(exp.get("anchor", ""))
            desc = exp.get("description", "")
            tex += rf"\noindent\textbf{{{anchor}}}" + "\n"
            if desc:
                tex += r"\begin{itemize}[leftmargin=14pt,itemsep=2pt,topsep=3pt,label={•}]" + "\n"
                lines = [l.strip() for l in desc.replace("•", "\n").replace("- ", "\n").split("\n") if l.strip()]
                for line in lines:
                    line_clean = esc(line.lstrip("-•* ").strip())
                    if line_clean:
                        tex += f"    \\item {line_clean}\n"
                tex += r"\end{itemize}" + "\n"
            tex += r"\vspace{4pt}" + "\n"

    projects = cv_data.get("projects", [])
    if projects:
        if not experience:
            tex += r"\section{Projects}" + "\n"
        for proj in projects:
            anchor = esc(proj.get("anchor", ""))
            desc = proj.get("description", "")
            tex += rf"\noindent\textbf{{{anchor}}}" + "\n"
            if desc:
                tex += r"\begin{itemize}[leftmargin=14pt,itemsep=2pt,topsep=3pt,label={•}]" + "\n"
                lines = [l.strip() for l in desc.replace("•", "\n").replace("- ", "\n").split("\n") if l.strip()]
                for line in lines:
                    line_clean = esc(line.lstrip("-•* ").strip())
                    if line_clean:
                        tex += f"    \\item {line_clean}\n"
                tex += r"\end{itemize}" + "\n"
            tex += r"\vspace{4pt}" + "\n"

    education = cv_data.get("education", [])
    if education:
        tex += r"\section{Education}" + "\n"
        for edu in education:
            anchor = esc(edu.get("anchor", ""))
            desc = esc(edu.get("description", ""))
            tex += rf"\noindent\textbf{{{anchor}}}\\" + "\n"
            if desc:
                tex += desc + "\n"
            tex += r"\vspace{4pt}" + "\n"

    certifications = cv_data.get("certifications", [])
    if certifications:
        tex += r"\section{Certifications \& Achievements}" + "\n"
        for cert in certifications:
            if isinstance(cert, dict):
                anchor = cert.get("anchor", "")
                title, subtitle, date_range = parse_anchor(anchor)
                tex += rf"\noindent\textbf{{\small {esc(title)}}}"
                if date_range:
                    tex += rf" \hfill \textcolor{{darkgray}}{{\small {esc(date_range)}}}"
                tex += r"\\[1pt]" + "\n"
            elif isinstance(cert, str):
                tex += rf"\noindent\textbf{{\small {esc(cert)}}}\\" + "\n"
            tex += r"\vspace{2pt}" + "\n"

    tex += r"\end{document}"
    return tex


def compile_latex_pdf(cv_data: dict) -> Optional[bytes]:
    """Try compiling LaTeX template to PDF using system compilers."""
    compiler = None
    for c in ["xelatex", "pdflatex", "lualatex"]:
        if shutil.which(c):
            compiler = c
            break

    if not compiler:
        logger.info("No system LaTeX compiler (pdflatex/xelatex) found. Falling back to FPDF2 engine.")
        return None

    try:
        tex_content = generate_latex_source(cv_data)
        with tempfile.TemporaryDirectory() as tmpdir:
            tex_path = os.path.join(tmpdir, "resume.tex")
            with open(tex_path, "w", encoding="utf-8") as f:
                f.write(tex_content)
            
            # Run compiler twice to resolve dynamic numbering/layout correctly
            for _ in range(2):
                res = subprocess.run(
                    [compiler, "-interaction=nonstopmode", "resume.tex"],
                    cwd=tmpdir,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    timeout=15
                )
                if res.returncode != 0:
                    logger.error(f"LaTeX compiler failed: {res.stderr.decode('utf-8', errors='ignore')}")
                    return None
            
            pdf_path = os.path.join(tmpdir, "resume.pdf")
            if os.path.exists(pdf_path):
                with open(pdf_path, "rb") as f:
                    return f.read()
    except Exception as e:
        logger.error(f"LaTeX compile engine failed: {e}")
    return None


def generate_cv_pdf(cv_data: dict) -> Optional[bytes]:
    """
    Main entry point: Generates PDF from structured CV data.
    First tries high-fidelity LaTeX compiler, falls back to custom beautiful FPDF.
    """
    # 1. Try High-Fidelity LaTeX Compiler First
    pdf_bytes = compile_latex_pdf(cv_data)
    if pdf_bytes:
        logger.info("Successfully rendered PDF using native LaTeX compiler engine!")
        return pdf_bytes

    # 2. Fallback to Beautiful FPDF-based Renderer
    logger.info("Rendering PDF using FPDF beautiful theme fallback.")
    return generate_fpdf_pdf(cv_data)
