"""
Task 3.2: ATS-Compliant PDF CV Generator.
Generates clean, professional PDFs from structured CV data extracted by NER.
Uses fpdf2 for lightweight PDF generation without system dependencies.

ATS (Applicant Tracking System) compliance:
- Simple, single-column layout
- Standard fonts (no custom fonts required)
- Clear section headers
- No tables, images, or complex formatting
- Proper text hierarchy
"""

import io
import logging
from typing import Optional
from datetime import datetime

logger = logging.getLogger(__name__)

try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False
    logger.warning("fpdf2 not installed. PDF generation will be unavailable. Install with: pip install fpdf2")


class ATSResumePDF(FPDF):
    """ATS-friendly PDF layout for professional CVs."""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        pass  # No header for ATS compliance

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by CV Assistant | {datetime.now().strftime('%Y-%m-%d')}", align="C")

    def add_name(self, name: str):
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(33, 37, 41)
        self.cell(0, 12, name, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def add_contact_line(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, text, align="C", new_x="LMARGIN", new_y="NEXT")

    def add_section_header(self, title: str):
        self.ln(6)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(33, 37, 41)
        self.cell(0, 8, title.upper(), new_x="LMARGIN", new_y="NEXT")
        # Divider line
        self.set_draw_color(200, 200, 200)
        self.set_line_width(0.5)
        y = self.get_y()
        self.line(10, y, 200, y)
        self.ln(4)

    def add_subsection(self, title: str, subtitle: str = "", date_range: str = ""):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(33, 37, 41)

        if date_range:
            # Title on left, date on right
            title_width = self.get_string_width(title) + 2
            self.cell(title_width, 6, title)
            self.set_font("Helvetica", "", 10)
            self.set_text_color(100, 100, 100)
            self.cell(0, 6, date_range, align="R", new_x="LMARGIN", new_y="NEXT")
        else:
            self.cell(0, 6, title, new_x="LMARGIN", new_y="NEXT")

        if subtitle:
            self.set_font("Helvetica", "I", 10)
            self.set_text_color(80, 80, 80)
            self.cell(0, 5, subtitle, new_x="LMARGIN", new_y="NEXT")

        self.ln(1)

    def add_bullet_point(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.set_x(15)
        # Use a simple dash as bullet
        self.multi_cell(0, 5, f"- {text}", new_x="LMARGIN", new_y="NEXT")

    def add_paragraph(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 5, text, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def add_skills_line(self, category: str, skills: list[str]):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(33, 37, 41)
        cat_width = self.get_string_width(category + ": ") + 2
        self.cell(cat_width, 6, f"{category}: ")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, ", ".join(skills), new_x="LMARGIN", new_y="NEXT")


def generate_cv_pdf(cv_data: dict) -> Optional[bytes]:
    """
    Generate an ATS-compliant PDF from structured CV data.

    Expected cv_data format (from NER parse-cv output):
    {
        "name": "Nguyen Van An",
        "email": "an@email.com",
        "phone": "0901234567",
        "location": "Ho Chi Minh City, Vietnam",
        "summary": "Professional summary text...",
        "experience": [
            {
                "anchor": "Software Developer, FPT Software (2020 - 2023)",
                "description": "bullet point descriptions",
                "entities": [...]
            }
        ],
        "education": [...],
        "skills": {"Programming": ["Python", "Java"], "Database": ["PostgreSQL"]},
        "certifications": [...],
        "projects": [...]
    }
    """
    if not HAS_FPDF:
        logger.error("fpdf2 not installed. Cannot generate PDF.")
        return None

    try:
        pdf = ATSResumePDF()
        pdf.add_page()

        # ─── Name & Contact ─────────────────────────────
        name = cv_data.get("name", "")
        if name:
            pdf.add_name(name)

        contact_parts = []
        if cv_data.get("email"):
            contact_parts.append(cv_data["email"])
        if cv_data.get("phone"):
            contact_parts.append(cv_data["phone"])
        if cv_data.get("location"):
            contact_parts.append(cv_data["location"])

        if contact_parts:
            pdf.add_contact_line(" | ".join(contact_parts))
            pdf.ln(4)

        # ─── Professional Summary ────────────────────────
        summary = cv_data.get("summary", "")
        if summary:
            pdf.add_section_header("Professional Summary")
            pdf.add_paragraph(summary)

        # ─── Experience ──────────────────────────────────
        experience = cv_data.get("experience", [])
        if experience:
            pdf.add_section_header("Professional Experience")
            for exp in experience:
                anchor = exp.get("anchor", "")
                # Try to parse role, company, dates from anchor
                pdf.add_subsection(anchor)

                desc = exp.get("description", "")
                if desc:
                    # Split by newlines or bullet-like patterns
                    lines = [l.strip() for l in desc.replace("•", "\n").replace("- ", "\n").split("\n") if l.strip()]
                    for line in lines:
                        line_clean = line.lstrip("-•* ").strip()
                        if line_clean:
                            pdf.add_bullet_point(line_clean)
                pdf.ln(2)

        # ─── Projects ────────────────────────────────────
        projects = cv_data.get("projects", [])
        if projects:
            pdf.add_section_header("Projects")
            for proj in projects:
                anchor = proj.get("anchor", "")
                pdf.add_subsection(anchor)
                desc = proj.get("description", "")
                if desc:
                    lines = [l.strip() for l in desc.replace("•", "\n").replace("- ", "\n").split("\n") if l.strip()]
                    for line in lines:
                        line_clean = line.lstrip("-•* ").strip()
                        if line_clean:
                            pdf.add_bullet_point(line_clean)
                pdf.ln(2)

        # ─── Education ───────────────────────────────────
        education = cv_data.get("education", [])
        if education:
            pdf.add_section_header("Education")
            for edu in education:
                anchor = edu.get("anchor", "")
                pdf.add_subsection(anchor)
                desc = edu.get("description", "")
                if desc:
                    pdf.add_paragraph(desc)

        # ─── Skills ──────────────────────────────────────
        skills = cv_data.get("skills", {})
        if skills:
            pdf.add_section_header("Technical Skills")
            if isinstance(skills, dict):
                for category, skill_list in skills.items():
                    if skill_list:
                        pdf.add_skills_line(category, skill_list)
            elif isinstance(skills, list):
                pdf.add_paragraph(", ".join(skills))

        # ─── Certifications ──────────────────────────────
        certifications = cv_data.get("certifications", [])
        if certifications:
            pdf.add_section_header("Certifications")
            for cert in certifications:
                if isinstance(cert, dict):
                    anchor = cert.get("anchor", "")
                    pdf.add_bullet_point(anchor)
                elif isinstance(cert, str):
                    pdf.add_bullet_point(cert)

        # Output
        return pdf.output()

    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        return None
