"""Role slug → group mapping for ITviec expertise areas.

Auto-generated by scripts/build_role_mapping.py — do not edit by hand.
Source: https://itviec.com/jobs-expertise-index (96 expertise areas).
"""

# slug → {name, group, group_name}
ROLE_GROUPS = {
    "ai-architect": {
        "group": "data_management_and_governance",
        "group_name": "Data Management & Governance",
        "name": "AI Architect"
    },
    "ai-machine-learning-engineer": {
        "group": "data_science_and_ai_machine_learning",
        "group_name": "Data Science & AI / Machine Learning",
        "name": "AI / Machine Learning Engineer"
    },
    "ai-researcher": {
        "group": "data_science_and_ai_machine_learning",
        "group_name": "Data Science & AI / Machine Learning",
        "name": "AI Researcher"
    },
    "analytics-engineer": {
        "group": "data_analytics_and_business_intelligence",
        "group_name": "Data Analytics & Business Intelligence",
        "name": "Analytics Engineer"
    },
    "application-security-engineer": {
        "group": "cybersecurity",
        "group_name": "Cybersecurity",
        "name": "Application Security Engineer"
    },
    "automation-tester": {
        "group": "software_testing_and_quality_assurance",
        "group_name": "Software Testing & Quality Assurance",
        "name": "Automation Tester"
    },
    "backend-developer": {
        "group": "web_application_development",
        "group_name": "Web Application Development",
        "name": "Backend Developer"
    },
    "banking-financial-systems-developer": {
        "group": "core_enterprise_systems_development",
        "group_name": "Core / Enterprise Systems Development",
        "name": "Banking & Financial Systems Developer"
    },
    "bi-analyst-bi-developer": {
        "group": "data_analytics_and_business_intelligence",
        "group_name": "Data Analytics & Business Intelligence",
        "name": "BI Analyst / BI Developer"
    },
    "big-data-engineer": {
        "group": "data_engineering",
        "group_name": "Data Engineering",
        "name": "Big Data Engineer"
    },
    "blockchain-architect": {
        "group": "blockchain_development",
        "group_name": "Blockchain Development",
        "name": "Blockchain Architect"
    },
    "blockchain-developer": {
        "group": "blockchain_development",
        "group_name": "Blockchain Development",
        "name": "Blockchain Developer"
    },
    "bridge-system-engineer-brse": {
        "group": "project_management_technical_communication",
        "group_name": "Project Management / Technical Communication",
        "name": "Bridge System Engineer (BrSE)"
    },
    "business-analyst": {
        "group": "project_management_technical_communication",
        "group_name": "Project Management / Technical Communication",
        "name": "Business Analyst"
    },
    "c-level-cto-cio-ciso-cdo": {
        "group": "it_executive_and_management",
        "group_name": "IT Executive and Management",
        "name": "C-level (CTO, CIO, CISO, CDO)"
    },
    "cloud-engineer": {
        "group": "cloud_computing",
        "group_name": "Cloud Computing",
        "name": "Cloud Engineer"
    },
    "compliance-officer-analyst": {
        "group": "it_compliance_and_risk_management",
        "group_name": "IT Compliance & Risk Management",
        "name": "Compliance Officer / Analyst"
    },
    "computer-vision-engineer": {
        "group": "data_science_and_ai_machine_learning",
        "group_name": "Data Science & AI / Machine Learning",
        "name": "Computer Vision Engineer"
    },
    "data-analyst": {
        "group": "data_analytics_and_business_intelligence",
        "group_name": "Data Analytics & Business Intelligence",
        "name": "Data Analyst"
    },
    "data-architect": {
        "group": "data_management_and_governance",
        "group_name": "Data Management & Governance",
        "name": "Data Architect"
    },
    "data-engineer": {
        "group": "data_engineering",
        "group_name": "Data Engineering",
        "name": "Data Engineer"
    },
    "data-governance-specialist": {
        "group": "data_management_and_governance",
        "group_name": "Data Management & Governance",
        "name": "Data Governance Specialist"
    },
    "data-scientist": {
        "group": "data_science_and_ai_machine_learning",
        "group_name": "Data Science & AI / Machine Learning",
        "name": "Data Scientist"
    },
    "data-steward-data-quality-analyst": {
        "group": "data_management_and_governance",
        "group_name": "Data Management & Governance",
        "name": "Data Steward / Data Quality Analyst"
    },
    "data-visualization-specialist": {
        "group": "data_analytics_and_business_intelligence",
        "group_name": "Data Analytics & Business Intelligence",
        "name": "Data Visualization Specialist"
    },
    "database-administrator": {
        "group": "data_management_and_governance",
        "group_name": "Data Management & Governance",
        "name": "Database Administrator"
    },
    "database-engineer": {
        "group": "data_engineering",
        "group_name": "Data Engineering",
        "name": "Database Engineer"
    },
    "dataops-mlops-engineer": {
        "group": "data_engineering",
        "group_name": "Data Engineering",
        "name": "DataOps / MLOps Engineer"
    },
    "desktop-application-developer": {
        "group": "core_enterprise_systems_development",
        "group_name": "Core / Enterprise Systems Development",
        "name": "Desktop Application Developer"
    },
    "devops-engineer": {
        "group": "devops_and_site_reliability_sre",
        "group_name": "DevOps & Site Reliability (SRE)",
        "name": "DevOps Engineer"
    },
    "devsecops-engineer": {
        "group": "cybersecurity",
        "group_name": "Cybersecurity",
        "name": "DevSecOps Engineer"
    },
    "edge-computing-engineer": {
        "group": "iot_and_robotics",
        "group_name": "IoT & Robotics",
        "name": "Edge Computing Engineer"
    },
    "embedded-engineer": {
        "group": "embedded_systems",
        "group_name": "Embedded Systems",
        "name": "Embedded Engineer"
    },
    "enterprise-application-consultant-crm-hcm-scm-and-other-enterprise-solutions": {
        "group": "it_consulting_and_sales",
        "group_name": "IT Consulting & Sales",
        "name": "Enterprise Application Consultant (CRM / HCM / SCM and other enterprise solutions)"
    },
    "enterprise-application-developer-crm": {
        "group": "core_enterprise_systems_development",
        "group_name": "Core / Enterprise Systems Development",
        "name": "Enterprise Application Developer (CRM)"
    },
    "enterprise-architect": {
        "group": "technical_architecture",
        "group_name": "Technical Architecture",
        "name": "Enterprise Architect"
    },
    "erp-consultant": {
        "group": "it_consulting_and_sales",
        "group_name": "IT Consulting & Sales",
        "name": "ERP Consultant"
    },
    "erp-developer": {
        "group": "core_enterprise_systems_development",
        "group_name": "Core / Enterprise Systems Development",
        "name": "ERP Developer"
    },
    "field-support": {
        "group": "it_support_and_helpdesk",
        "group_name": "IT Support & Helpdesk",
        "name": "Field Support"
    },
    "firmware-engineer": {
        "group": "embedded_systems",
        "group_name": "Embedded Systems",
        "name": "Firmware Engineer"
    },
    "frontend-developer": {
        "group": "web_application_development",
        "group_name": "Web Application Development",
        "name": "Frontend Developer"
    },
    "fullstack-developer": {
        "group": "web_application_development",
        "group_name": "Web Application Development",
        "name": "Fullstack Developer"
    },
    "game-designer": {
        "group": "game_development",
        "group_name": "Game Development",
        "name": "Game Designer"
    },
    "game-developer": {
        "group": "game_development",
        "group_name": "Game Development",
        "name": "Game Developer"
    },
    "game-producer-director": {
        "group": "game_development",
        "group_name": "Game Development",
        "name": "Game Producer / Director"
    },
    "game-tester": {
        "group": "game_development",
        "group_name": "Game Development",
        "name": "Game Tester"
    },
    "grc-specialist": {
        "group": "it_compliance_and_risk_management",
        "group_name": "IT Compliance & Risk Management",
        "name": "GRC Specialist"
    },
    "hardware-software-integration-engineer": {
        "group": "embedded_systems",
        "group_name": "Embedded Systems",
        "name": "Hardware-Software Integration Engineer"
    },
    "integration-legacy-systems-developer": {
        "group": "core_enterprise_systems_development",
        "group_name": "Core / Enterprise Systems Development",
        "name": "Integration & Legacy Systems Developer"
    },
    "iot-application-developer": {
        "group": "iot_and_robotics",
        "group_name": "IoT & Robotics",
        "name": "IoT Application Developer"
    },
    "it-administrator": {
        "group": "it_support_and_helpdesk",
        "group_name": "IT Support & Helpdesk",
        "name": "IT Administrator"
    },
    "it-auditor-it-risk-manager": {
        "group": "it_compliance_and_risk_management",
        "group_name": "IT Compliance & Risk Management",
        "name": "IT Auditor / IT Risk Manager"
    },
    "it-communicator": {
        "group": "project_management_technical_communication",
        "group_name": "Project Management / Technical Communication",
        "name": "IT Communicator"
    },
    "it-consultant": {
        "group": "it_consulting_and_sales",
        "group_name": "IT Consulting & Sales",
        "name": "IT Consultant"
    },
    "it-helpdesk": {
        "group": "it_support_and_helpdesk",
        "group_name": "IT Support & Helpdesk",
        "name": "IT Helpdesk"
    },
    "it-support": {
        "group": "it_support_and_helpdesk",
        "group_name": "IT Support & Helpdesk",
        "name": "IT Support"
    },
    "low-code-no-code-developer": {
        "group": "low_code_no_code_development",
        "group_name": "Low-Code / No-Code Development",
        "name": "Low-Code/No-Code Developer"
    },
    "manager": {
        "group": "it_executive_and_management",
        "group_name": "IT Executive and Management",
        "name": "Manager"
    },
    "manual-tester": {
        "group": "software_testing_and_quality_assurance",
        "group_name": "Software Testing & Quality Assurance",
        "name": "Manual Tester"
    },
    "mobile-application-developer": {
        "group": "mobile_application_development",
        "group_name": "Mobile Application Development",
        "name": "Mobile Application Developer"
    },
    "motion-designer": {
        "group": "design_and_user_experience",
        "group_name": "Design & User Experience",
        "name": "Motion Designer"
    },
    "network-engineer": {
        "group": "systems_and_network_engineering_administration",
        "group_name": "Systems & Network Engineering / Administration",
        "name": "Network Engineer"
    },
    "performance-load-tester": {
        "group": "software_testing_and_quality_assurance",
        "group_name": "Software Testing & Quality Assurance",
        "name": "Performance / Load Tester"
    },
    "pre-sales-engineer": {
        "group": "it_consulting_and_sales",
        "group_name": "IT Consulting & Sales",
        "name": "Pre-sales Engineer"
    },
    "process-quality-assurance-pqa": {
        "group": "software_testing_and_quality_assurance",
        "group_name": "Software Testing & Quality Assurance",
        "name": "Process Quality Assurance (PQA)"
    },
    "product-analyst": {
        "group": "product_management",
        "group_name": "Product Management",
        "name": "Product Analyst"
    },
    "product-designer": {
        "group": "design_and_user_experience",
        "group_name": "Design & User Experience",
        "name": "Product Designer"
    },
    "product-manager": {
        "group": "product_management",
        "group_name": "Product Management",
        "name": "Product Manager"
    },
    "product-owner": {
        "group": "product_management",
        "group_name": "Product Management",
        "name": "Product Owner"
    },
    "program-manager-pmo": {
        "group": "project_management_technical_communication",
        "group_name": "Project Management / Technical Communication",
        "name": "Program Manager / PMO"
    },
    "project-manager": {
        "group": "project_management_technical_communication",
        "group_name": "Project Management / Technical Communication",
        "name": "Project Manager"
    },
    "real-time-systems-engineer": {
        "group": "embedded_systems",
        "group_name": "Embedded Systems",
        "name": "Real-Time Systems Engineer"
    },
    "release-manager": {
        "group": "devops_and_site_reliability_sre",
        "group_name": "DevOps & Site Reliability (SRE)",
        "name": "Release Manager"
    },
    "robotics-software-engineer": {
        "group": "iot_and_robotics",
        "group_name": "IoT & Robotics",
        "name": "Robotics Software Engineer"
    },
    "rpa-engineer": {
        "group": "core_enterprise_systems_development",
        "group_name": "Core / Enterprise Systems Development",
        "name": "RPA Engineer"
    },
    "scrum-master-agile-coach": {
        "group": "project_management_technical_communication",
        "group_name": "Project Management / Technical Communication",
        "name": "Scrum Master / Agile Coach"
    },
    "security-consultant": {
        "group": "cybersecurity",
        "group_name": "Cybersecurity",
        "name": "Security Consultant"
    },
    "security-engineer": {
        "group": "cybersecurity",
        "group_name": "Cybersecurity",
        "name": "Security Engineer"
    },
    "security-tester-penetration-tester": {
        "group": "cybersecurity",
        "group_name": "Cybersecurity",
        "name": "Security Tester / Penetration Tester"
    },
    "site-reliability-engineer-sre": {
        "group": "devops_and_site_reliability_sre",
        "group_name": "DevOps & Site Reliability (SRE)",
        "name": "Site Reliability Engineer (SRE)"
    },
    "smart-contract-developer": {
        "group": "blockchain_development",
        "group_name": "Blockchain Development",
        "name": "Smart Contract Developer"
    },
    "software-engineer-in-test-sdet": {
        "group": "software_testing_and_quality_assurance",
        "group_name": "Software Testing & Quality Assurance",
        "name": "Software Engineer in Test (SDET)"
    },
    "software-technical-architect": {
        "group": "technical_architecture",
        "group_name": "Technical Architecture",
        "name": "Software/Technical Architect"
    },
    "solution-architect": {
        "group": "technical_architecture",
        "group_name": "Technical Architecture",
        "name": "Solution Architect"
    },
    "sysops-engineer": {
        "group": "systems_and_network_engineering_administration",
        "group_name": "Systems & Network Engineering / Administration",
        "name": "SysOps Engineer"
    },
    "systems-engineer-administrator": {
        "group": "systems_and_network_engineering_administration",
        "group_name": "Systems & Network Engineering / Administration",
        "name": "Systems Engineer / Administrator"
    },
    "technical-account-manager": {
        "group": "it_consulting_and_sales",
        "group_name": "IT Consulting & Sales",
        "name": "Technical Account Manager"
    },
    "technical-consultant": {
        "group": "it_consulting_and_sales",
        "group_name": "IT Consulting & Sales",
        "name": "Technical Consultant"
    },
    "technical-customer-support": {
        "group": "it_support_and_helpdesk",
        "group_name": "IT Support & Helpdesk",
        "name": "Technical Customer Support"
    },
    "technical-writer": {
        "group": "project_management_technical_communication",
        "group_name": "Project Management / Technical Communication",
        "name": "Technical Writer"
    },
    "test-coordinator-qaqc-coordinator": {
        "group": "software_testing_and_quality_assurance",
        "group_name": "Software Testing & Quality Assurance",
        "name": "Test Coordinator / QAQC Coordinator"
    },
    "ux-researcher": {
        "group": "design_and_user_experience",
        "group_name": "Design & User Experience",
        "name": "UX Researcher"
    },
    "ux-ui-designer": {
        "group": "design_and_user_experience",
        "group_name": "Design & User Experience",
        "name": "UX/UI Designer"
    },
    "vice-president-director": {
        "group": "it_executive_and_management",
        "group_name": "IT Executive and Management",
        "name": "Vice President / Director"
    },
    "visual-graphic-designer": {
        "group": "design_and_user_experience",
        "group_name": "Design & User Experience",
        "name": "Visual / Graphic Designer"
    },
    "vr-ar-game-developer": {
        "group": "game_development",
        "group_name": "Game Development",
        "name": "VR/AR Game Developer"
    }
}
